[internal]

exten => 7001,1,Answer()
 same => n,Dial(PJSIP/7001,60)
 same => n,Playback(vm-nobodyavail)
 same => n,VoiceMail(7001@main)
 same => n,Hangup()

exten => 7002,1,Answer()
 same => n,Dial(PJSIP/7002,60)
 same => n,Playback(vm-nobodyavail)
 same => n,VoiceMail(7002@main)
 same => n,Hangup()

exten => 8001,1,VoicemailMain(7001@main)
 same => n,Hangup()

exten => 8002,1,VoicemailMain(7002@main)
 same => n,Hangup()
